import { Dimensions, StyleSheet } from 'react-native';
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from 'react-native-responsive-screen';
import { Palette } from 'App/Theme/Palette';
import { RFValue } from 'react-native-responsive-fontsize';
import { responsiveByHeight as rh, responsiveByWidth as rw } from 'App/Utils/style';
import { DEFAULT_LETTER_SPACING } from 'App/Utils/constants';
const screenWidth = Dimensions.get('screen').width;
export default StyleSheet.create({
  styleViewBorder: { backgroundColor: 'transparent' },
  styleTitleBack: { fontSize: 24, fontWeight: '700', color: '#fff' },
  viewContainer: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    zIndex: 1,
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
  },
  icLeftHeaderStyle: {
    justifyContent: 'center',
    marginLeft: 20,
  },
  styleHeader: {
    position: 'absolute',
    width: wp('100%'),
  },
  styleTitle: {
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 22,
    color: Palette.white,
    marginLeft: 12,
  },
  content: {
    //position: "absolute",
    backgroundColor: Palette.color_F5F5F5,
    // width: wp('100'),
    marginTop: 100,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    // height: hp('100'),
  },
  viewContent: {
    backgroundColor: Palette.white,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  styleheaderConten: {
    flexDirection: 'row',
  },
  txtOrderCode: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    color: Palette.zaapi4,
  },
  txtDateTime: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    color: Palette.zaapi4,
    display: 'flex',
    alignItems: 'center',
  },
  line: { borderWidth: 1, borderColor: Palette.color_E5E5E5, marginTop: 12, marginBottom: 20 },
  txtlengListOrder: {
    color: Palette.zaapi4,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 17.6,
    alignItems: 'center',
    display: 'flex',
  },
  imageProduct: {
    resizeMode: 'contain',
    width: 62,
    height: 62,
    borderRadius: 12,
  },
  viewItem: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    paddingVertical: 12,
    borderColor: Palette.color_F5F5F5,
  },
  viewContentiem: {
    marginLeft: 13,
    flex: 1,
  },
  txtNameProduct: {
    color: Palette.zaapi4,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 17.6,
    display: 'flex',
    alignItems: 'center',
  },
  typeItem: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 17.6,
    color: Palette.zaapi4,
  },
  typeContenItem: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17.6,
    color: Palette.zaapi4,
  },
  txtPriceItem: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    color: Palette.zaapi4,
  },
  txtoldPriceItem: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 15.08,
    textAlign: 'right',
    marginTop: 2,
    color: Palette.grey,
    textDecorationLine: 'line-through',
  },
  txttypetotal: {
    flex: 1,
    color: Palette.zaapi4,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
  },
  txttotal: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 17.6,
    textAlign: 'right',
    display: 'flex',
    alignItems: 'center',
    color: Palette.zaapi4,
  },
  txttypetotalall: {
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 22.63,
    color: Palette.zaapi4,
    flex: 1,
  },
  txttotalall: {
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 22.63,
    textAlign: 'right',
    display: 'flex',
    alignItems: 'center',
    color: Palette.zaapi2,
  },
  viewDeliveryAddress: {
    paddingVertical: 30,
    paddingHorizontal: 16,
    marginBottom: rh(10),
    marginTop: 10,
    backgroundColor: Palette.white,
  },
  txtDeliveryAddress: {
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 23,
    color: Palette.zaapi2,
  },
  txtName: {
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 23,
    display: 'flex',
    flex: 1,
    color: Palette.zaapi4,
  },
  viewCopy: {
    flexDirection: 'row',
  },
  viewName: {
    flexDirection: 'row',
    marginTop: rh(28),
    marginBottom: rh(10),
  },
  txtCopy: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 18,
    alignItems: 'center',
    display: 'flex',
    color: Palette.zaapi2,
    marginLeft: 6,
  },
  ViewPhoneNumber: {
    flexDirection: 'row',
    marginTop: 14,
  },
  customerInfoText: {
    fontWeight: '400',
    fontSize: rh(14),
    lineHeight: rh(18),
    display: 'flex',
    color: Palette.zaapi4,
    marginLeft: rw(12),
    alignItems: 'center',
    letterSpacing: rh(14) * DEFAULT_LETTER_SPACING,
    marginTop: rh(4),
    textAlignVertical: 'center',
  },
  ViewAddress: {
    flexDirection: 'row',
    marginTop: 20,
    marginRight: 100,
  },
  btnBottom: {
    flexDirection: 'row',
    padding: 11,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Palette.color_D6D6D6,
    borderRadius: 12,
    marginTop: 38,
    justifyContent: 'center',
  },
  txtcall: {
    fontSize: 16,
    lineHeight: 20,
    display: 'flex',
    alignItems: 'center',
    color: Palette.black,
    marginLeft: 11,
  },
  viewPayment: {},
  txtPayment: {
    flex: 1,
    color: Palette.zaapi4,
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
  },
  txtNopayment: {
    fontSize: 14,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
  },
  imagePayment: {
    resizeMode: 'contain',
    width: 94,
    height: 94,
    marginTop: 10,
  },
  viewMarkasPaid: {
    flexDirection: 'row',
    marginTop: 33,
  },
  txtMarkasPaid: {
    flex: 1,
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
  },
  checkboxContainer: {
    flexDirection: 'row',
    marginBottom: rh(20),
    marginTop: rh(30),
    alignItems: 'center',
  },
  checkbox: {
    alignSelf: 'center',
    height: 24,
    width: 24,
  },
  label: {
    margin: 8,
    fontWeight: '600',
    fontSize: RFValue(14, 680),
    color: Palette.zaapi4,
    lineHeight: 21,
  },
  viewBottom: {
    flexDirection: 'row',
    marginTop: 50,
    marginBottom: 20,
  },
  btnReject: {
    width: '50%',
    marginRight: 2,
  },
  btnAccept: {
    width: '50%',
    marginLeft: 2,
  },
  formItem: {
    //height: rh(18) + 6 + 42 + 30,
    marginTop: rh(30),
  },
  formItemTitle: {
    fontWeight: '700',
    fontSize: rh(14),
    marginBottom: rh(6),
    flex: 1,
  },
  requiredMark: {
    color: Palette.error,
  },
  categoryTypeDropdownSelect: {
    width: screenWidth - 16 * 2,
    marginBottom: 8,
    // minHeight: 52,
  },
  viewPaymentReject: {
    paddingTop: 30,
    backgroundColor: Palette.white,
    paddingHorizontal: 16,
    marginBottom: 30,
  },
  customerInfoIcon: {
    width: rh(28),
    height: rh(28),
  },
  customerInfoDivider: {
    height: rh(1),
    marginTop: rh(30),
    backgroundColor: Palette.color_F5F5F5,
    marginHorizontal: rw(12),
  },
});
